title: Learning how to use Github 
author: Phetho Macmillian Malope
email: pmalope@student.wethinkcode.co.za
description: > # this means to ignore newlines until "baseurl:"
  There's no place like 127.0.0.1 :house:

# social links
twitter_username: martian1431 # DO NOT include the @ character, or else the build will fail!
github_username:  martian1431 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
